app/urls.py
from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    re_path(r'^.*\.html', views.gentella_html, name='gentella'),

    # The home page
    path('', views.index, name='index'),
]

gentelella/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # app/ -> Genetelella UI and resources
    url(r'^app/', include('app.urls')),
    url(r'^', include('app.urls')),
    # login
    url(r'index/$', views.index, name='index'),
    url(r'login/$', views.login, name='login'),
    url(r'register/$', views.register, name='register'),
    url(r'logout/$', views.logout),   
    # groups
    url(r'group_list/$', views.group_list, name='group_list'),
    url(r'join_group/$', views.join_group, name='join_group'),
    url(r'quit_group/$', views.quit_group, name='quit_group'),
    url(r'create_group/$', views.create_group, name='create_group'),
    #group
    url(r'group_info/$', views.group_info, name='group_info'),
    #event
    url(r'event_info/$', views.event_info, name='event_info'),
    url(r'add_event/$', views.add_event, name='add_event'),   
    #voting
    url(r'vote/$', views.vote, name='vote'),
    #movie
    url(r'movie_info/$', views.movie_info, name='movie_info'),
    url(r'add_movie/$', views.add_movie, name='add_movie'),
    url(r'search_movie/$', views.search_movie, name='search_movie'),
    url(r'view_movie/$', views.view_movie, name='view_movie'),
    
]

app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Movie(models.Model):
    m_id= models.CharField(primary_key=True,max_length=32)
    name= models.CharField(max_length=64)
    director= models.CharField(max_length=64,null=True, blank=True)
    year= models.CharField(max_length=4,null=True, blank=True)
    rating= models.CharField(max_length=4,null=True, blank=True)
    duration= models.CharField(max_length=4,null=True, blank=True)
    trailer= models.URLField(null=True, blank=True)
    review= models.URLField(null=True, blank=True)
    cover= models.URLField(null=True, blank=True)
    
    def __str__(self):
        return self.name 

class Group(models.Model):
    name= models.CharField(max_length=64, unique=True)
    moderator= models.CharField(max_length=64)
    c_time= models.DateTimeField(auto_now_add= True)
    movies= models.ManyToManyField(Movie)

    def __str__(self):
        return self.name 
    class Meta:
        ordering= ["-c_time"]
        verbose_name= "Group"
        verbose_name_plural= "Group"

class User(models.Model):
    name= models.CharField(max_length=64,unique=True)
    password= models.CharField(max_length=64)
    email= models.EmailField(unique=True)
    c_time= models.DateTimeField(auto_now_add= True)

    members= models.ManyToManyField(Group, through='Membership')

    def __str__(self):
        return self.name
    class Meta:
        ordering= ["-c_time"]
        verbose_name= "User"
        verbose_name_plural= "User"

class Membership(models.Model):
    member = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    date_joined = models.DateTimeField(auto_now_add= True)
    title = models.CharField(choices=(('Moderator','Moderator'),('Member','Member')),default='Member',max_length=10)

    class Meta:
        unique_together=("member","group")

class Event(models.Model):
    name= models.CharField(max_length=64)
    group= models.ForeignKey(Group, on_delete=models.CASCADE)
    start= models.DateTimeField()
    end= models.DateTimeField()
    movie= models.ForeignKey(Movie, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class Voting(models.Model):
    event= models.ForeignKey(Event, on_delete=models.CASCADE, unique=True)
    group= models.ForeignKey(Group, on_delete=models.CASCADE)
    movies= models.ManyToManyField(Movie, through='Votes')

    def __str__(self):
        return self.event.name

class Votes(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voting = models.ForeignKey(Voting, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)

    class Meta:
        ordering= ["-count"]

class HasVoted(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    voting = models.ForeignKey(Voting, on_delete=models.CASCADE)

app/templates/main/group_info.html
{% extends "frame/base_site.html" %}

{% block title %} Group {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/pnotify/dist/pnotify.css" rel="stylesheet">
  <link href="/static/vendors/pnotify/dist/pnotify.buttons.css" rel="stylesheet">
  <link href="/static/vendors/pnotify/dist/pnotify.nonblock.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Group {{membership.group.name}} - {{membership.title}}</h3>
        </div>
        <div class="btn-group">
            <form action="/group_info/", method="get">
                {% csrf_token %}
            <input name="group_id", id="group_id" hidden>  
            <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button"> Select Group <span class="caret"></span> </button>
            <ul class="dropdown-menu">
            {% for member in group_list %}
              <li><button class="btn btn-default dropdown-toggle" type="submit",
                onclick="document.getElementById('group_id').value = '{{member.group.id}}';">{{member.group.name}} - {{member.title}}</button></li>
              {% endfor %}
            </ul>
            </form>
          </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><i class="fa fa-bars"></i> Members </h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                      <thead>
                        <tr class="headings">
                          <th class="column-title">ID</th>
                          <th class="column-title">Name </th>
                          <th class="column-title">Joined Time</th>
                          <th class="column-title">Title</th>
                          <th class="column-title">Action </th>
                        </tr>
                      </thead>
                      <form action="/group_info/", method="get">
                        {% csrf_token %}
                        <input name="user_id" id="user_id" hidden>  
                        <input name="group_id" id="group_id" value="{{membership.group.id}}" hidden>  
                      <tbody>
                        {% for user in user_list %}
                        <tr class="">
                          <td class="">{{user.member.id}}</td>
                          <td class="">{{user.member.name}}</td>
                          <td class="">{{user.date_joined}}</td>
                          <td class="">{{user.title}}</td>                         
                          <td class="">
                            <button class="btn, btn-danger", type="submit", disabled="true",
                            onclick="document.getElementById('user_id').value ='{{user.member.id}}';">Remove</button>
                          </td>  
                        </tr>         
                        {% endfor %}
                      </tbody>          
                      </form>      
                    </table>
                  </div>
            </div>
          </div>
        </div>   
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><i class="fa fa-bars"></i> Events </h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <form action="/event_info/", method="get">
                <input name="group_id1", id="group_id1", value="{{membership.group.id}}" hidden>    
                <input name="event_id" id="event_id" hidden>    
                {% csrf_token %}
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                      <thead>
                        <tr class="headings">
                          <th class="column-title">Event ID</th>
                          <th class="column-title">Event Name</th>
                          <th class="column-title">Start Time</th>
                          <th class="column-title">End Time</th>
                          <th class="column-title">Movie</th>
                          <th class="column-title">Voting</th>
                          <th class="column-title">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for event in membership.group.event_set.all %}
                        <tr class="">
                          <td class="">{{event.id}}</td>
                          <td class="">{{event.name}}</td>
                          <td class="">{{event.start}}</td>  
                          <td class="">{{event.end}}</td>
                          <td class="">{{event.movie.name}}</td>
                          <td class="">{{event.voting_set.exists}}</td>                           
                          <td class="">
                            <button class="btn, btn-success", type="submit",
                            onclick="document.getElementById('event_id').value = '{{event.id}}';">View</button>
                          </td>  
                        </tr>       
                        {% endfor %}
                      </tbody>                              
                    </table>
                    <button class="btn btn-primary" type="submit" id="new_event" disabled="true",
                    onclick="document.getElementById('event_id').value =null;">New Event</button> 
                </div>
                    
              </form>          
              </div>
          </div>
        </div>   
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><i class="fa fa-bars"></i> Movies </h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="table-responsive">
                  <table class="table table-striped jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th class="column-title">ID</th>
                        <th class="column-title">Name</th>
                        <th class="column-title">Director</th>
                        <th class="column-title">Year</th>
                        <th class="column-title">Duration</th>
                        <th class="column-title">Ratingg</th>
                        <th class="column-title">Action</th>
                      </tr>
                    </thead>
                    <form action="/view_movie/", method="get">
                      {% csrf_token %}
                      <input name="m_id" id="m_id" hidden>   
                    <tbody>
                      {% for movie in movie_list %}
                      <tr class="">
                        <td class="">{{movie.m_id}}</td>
                        <td class="">{{movie.name}}</td>
                        <td class="">{{movie.director}}</td>
                        <td class="">{{movie.year}}</td>  
                        <td class="">{{movie.duration}}</td>
                        <td class="">{{movie.rating}}</td>                    
                        <td class="">
                          <button class="btn, btn-success", type="submit",
                          onclick="document.getElementById('m_id').value = '{{movie.m_id}}';">View</button>
                        </td>  
                      </tr>       
                      {% endfor %}
                    </tbody> 
                    </form>                             
                  </table>
                </div>
            </div>
          </div>
        </div>   
      </div>
      
    <div class="clearfix"></div>
  </div>

  <script>
    function access(title) {
      if(title === "Moderator")
      {
        document.getElementById("new_event").disabled=false;
        remove_list= document.getElementsByClassName("btn, btn-danger");
        for(var i= 0; i< remove_list.length; i++)
          remove_list[i].disabled=false;
      }     
    }
    window.onload= access('{{membership.title}}')
    </script>
{% endblock content %}

app/templates/main/group_list.html
{% extends "frame/base_site.html" %}

{% block title %} Groups {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/pnotify/dist/pnotify.css" rel="stylesheet">
  <link href="/static/vendors/pnotify/dist/pnotify.buttons.css" rel="stylesheet">
  <link href="/static/vendors/pnotify/dist/pnotify.nonblock.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Group List</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><i class="fa fa-bars"></i> Created Groups </h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <div class="table-responsive">
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">ID</th>
                      <th class="column-title">Name </th>
                      <th class="column-title">Created Time</th>
                      <th class="column-title">Moderator</th>
                      <th class="column-title">Users</th>
                      <th class="column-title">Events </th>
                      <th class="column-title">Votings </th>
                      <th class="column-title no-link last"><span class="nobr">Action</span>
                      </th>
                    </tr>
                  </thead>
                  <form action="/quit_group/", method="get">
                    {% csrf_token %}
                  <tbody>
                    {% for group in created %}
                    <tr class="">
                      <td class="">{{group.id}}</td>
                      <td class="">{{group.name}}</td>
                      <td class="">{{group.c_time}}</td>
                      <td class="">{{group.moderator}}</td>
                      <td class="">{{group.user_set.count}}</td>
                      <td class="">{{group.event_set.count}}</td>
                      <td class="">{{group.voting_set.count}}</td>
                      <td class="">
                        <button class="btn, btn-success", type="button", href="#">View</button>
                      </td>  
                      </td>
                    </tr>             
                    <input name="group_id", value="{{group.id}}" hidden>   
                    {% endfor %}
                  </tbody>
                  </form>
                </table>
              </div>
            </div>
          </div>
        </div>   
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><i class="fa fa-bars"></i> Joined Groups </h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <div class="table-responsive">
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">ID</th>
                      <th class="column-title">Name </th>
                      <th class="column-title">Created Time</th>
                      <th class="column-title">Moderator</th>
                      <th class="column-title">Users</th>
                      <th class="column-title">Events </th>
                      <th class="column-title">Votings </th>
                      <th class="column-title no-link last"><span class="nobr">Action</span>
                      </th>
                    </tr>
                  </thead>
                  <form action="/quit_group/", method="get">
                    {% csrf_token %}
                    <input name="group_id", id="group_id" hidden>   
                  <tbody>
                    {% for group in joined %}
                    <tr class="">
                      <td class="">{{group.id}}</td>
                      <td class="">{{group.name}}</td>
                      <td class="">{{group.c_time}}</td>
                      <td class="">{{group.moderator}}</td>
                      <td class="">{{group.user_set.count}}</td>
                      <td class="">{{group.event_set.count}}</td>
                      <td class="">{{group.voting_set.count}}</td>
                      <td class="">
                        <button class="btn, btn-success", type="submit", 
                        onclick="document.getElementById('group_id').value = '{{group.id}}';">Unsubscribe</button>
                      </td>  
                      </td>
                    </tr>             
                    {% endfor %}
                  </tbody>
                  </form>
                </table>
              </div>
            </div>
          </div>
        </div>   
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><i class="fa fa-bars"></i> Other Groups </h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <div class="table-responsive">
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th class="column-title">ID</th>
                      <th class="column-title">Name </th>
                      <th class="column-title">Created Time</th>
                      <th class="column-title">Moderator</th>
                      <th class="column-title">Users</th>
                      <th class="column-title">Events </th>
                      <th class="column-title">Votings </th>
                      <th class="column-title">Action </th>
                    </tr>
                  </thead>
                  <form action="/join_group/", method="get">
                    {% csrf_token %}
                    <input name="group_id", id="group_id1" hidden>           
                  <tbody>
                    {% for group in other %}
                    <tr class="">
                      <td class="">{{group.id}}</td>
                      <td class="">{{group.name}}</td>
                      <td class="">{{group.c_time}}</td>
                      <td class="">{{group.moderator}}</td>
                      <td class="">{{group.user_set.count}}</td>
                      <td class="">{{group.event_set.count}}</td>
                      <td class="">{{group.voting_set.count}}</td>  
                      <td class="">
                        <button class="btn, btn-success", type="submit", 
                        onclick="document.getElementById('group_id1').value = '{{group.id}}';">Join</button>
                      </td>  
                    </tr>
                    {% endfor %}
                  </tbody>          
                  </form>      
                </table>
              </div>
            </div>
          </div>
        </div>   
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <h2><i class="fa fa-bars"></i> New Group </h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <form id="demo-form2" action="/create_group/" method="get" data-parsley-validate class="form-horizontal form-label-left">
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="group_name">Group name</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" name="group_name" required="required" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>

                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="group_title">Group title</label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" name="group_title" disabled="disabled" value="Moderator" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
  		              <button class="btn btn-primary" type="reset">Reset</button>
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>
                </div>

              </form>
            </div>
          </div>
        </div>   
      </div>

    <div class="clearfix"></div>
  </div>
{% endblock content %}